### ISSUE TITLE
Rien ne fonctionne plus

### ISSUE THREAD

**Issue by AXDOOMER** [scarpentier/ETS-Rez-Net-Usage#5]
Peu importe ce que je fais, avec n'importe quel numéro d'appartement ou phase, ça me donne ça:
![untitled](https://cloud.githubusercontent.com/assets/6194072/21777163/b32ce4fc-d66b-11e6-8825-64cb53e50d6e.png)

**Comment by scarpentier** [comment]
Gracieusement réparé par @cmccauley dans #6

**Comment by scarpentier** [comment]
Causé par Cooptel qui a changé comment la page source est présentée
